services:
  
  nginx:
    image: umputun/nginx-le:latest
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"
    volumes:
    #  - ./ssl:/etc/nginx/ssl
      - ./index.html:/srv/docroot/project2/index.html
    # ports:
    #   - 80:80
    #   - 443:443
    environment:
      - TZ=Europe/Moscow
      # - LETSENCRYPT=true
      # - LE_EMAIL=tech-support@nevatrip.ru
      # - LE_FQDN=project2.nevatrip.ru
    tty: true
    networks:
      - projects
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.proj2.rule=Host(`superevilmegacorp.com`)"
      - "traefik.http.routers.proj2.entrypoints=websecure"
      - "traefik.http.routers.proj2.tls.certresolver=evilcorp"
      - "traefik.http.routers.proj2.tls=true"

networks:
  projects:
